import json
from typing import Dict, List
from joblib import load
from flask import Flask, render_template, request, jsonify
import pandas as pd

# Flask
app =  Flask(__name__)

# loading models and transfomers
clf, model_cols,  scaler, labelencoder = load('/Users/carlysethomas/Desktop/Project_4/ML_models_mine.sav')

@app.route('/')
def home():
    return render_template("index.html")

@app.route("/visualizations.html")
def visuals():
    return render_template("visualizations.html")

@app.route('/index.html')
def index():
    return render_template("index.html")

@app.route("/moreinfo.html")
def more():
    return render_template("moreinfo.html")

list_one = ['Rating','Location_Addison, TX',
 'Location_Alachua, FL',
 'Location_Alameda, CA',
 'Location_Alhambra, CA',
 'Location_Allegheny West, PA',
 'Location_Allen, TX',
 'Location_American Fork, UT',
 'Location_Anaheim, CA',
 'Location_Arcadia, CA',
 'Location_Arlington Heights, IL',
 'Location_Arlington, TX',
 'Location_Athens, GA',
 'Location_Aurora, CO',
 'Location_Austin, TX',
 'Location_Azusa, CA',
 'Location_Beech Grove, IN',
 'Location_Bellevue, WA',
 'Location_Bensalem, PA',
 'Location_Berkeley Heights, NJ',
 'Location_Berkeley, CA',
 'Location_Berwyn, PA',
 'Location_Beverly Hills, CA',
 'Location_Blue Bell, PA',
 'Location_Boothwyn, PA',
 'Location_Boulder, CO',
 'Location_Brea, CA',
 'Location_Bridgeview, IL',
 'Location_Broadview, IL',
 'Location_Bronx, NY',
 'Location_Brooklyn, NY',
 'Location_Broomfield, CO',
 'Location_Burbank, CA',
 'Location_Burlingame, CA',
 'Location_Burlingame, KS',
 'Location_Camden, NJ',
 'Location_Campbell, CA',
 'Location_Carmel, IN',
 'Location_Carrollton, TX',
 'Location_Cedar Park, TX',
 'Location_Centennial, CO',
 'Location_Cerritos, CA',
 'Location_Chandler, AZ',
 'Location_Charlotte, NC',
 'Location_Chesapeake, VA',
 'Location_Chester Township, PA',
 'Location_Chicago, IL',
 'Location_City of Industry, CA',
 'Location_Columbus, OH',
 'Location_Conshohocken, PA',
 'Location_Coppell, TX',
 'Location_Culver City, CA',
 'Location_Cupertino, CA',
 'Location_DC Ranch, AZ',
 'Location_Dallas, TX',
 'Location_Daly City, CA',
 'Location_Deerfield, IL',
 'Location_Denver, CO',
 'Location_Downers Grove, IL',
 'Location_Doylestown, PA',
 'Location_Draper, UT',
 'Location_Dublin, OH',
 'Location_East Palo Alto, CA',
 'Location_El Cajon, CA',
 'Location_El Segundo, CA',
 'Location_Elk Grove Village, IL',
 'Location_Emeryville, CA',
 'Location_Englewood, CO',
 'Location_Essex Fells, NJ',
 'Location_Evanston, IL',
 'Location_Exton, PA',
 'Location_Farmers Branch, TX',
 'Location_Feasterville Trevose, PA',
 'Location_Florham Park, NJ',
 'Location_Fort Eustis, VA',
 'Location_Fort Lee, NJ',
 'Location_Fort Mill, SC',
 'Location_Fort Washington, PA',
 'Location_Fort Worth, TX',
 'Location_Foster City, CA',
 'Location_Franklin Lakes, NJ',
 'Location_Fremont, CA',
 'Location_Gainesville, FL',
 'Location_Gardena, CA',
 'Location_Glendale, AZ',
 'Location_Glendale, CA',
 'Location_Glenview, IL',
 'Location_Grapevine, TX',
 'Location_Greenwood Village, Arapahoe, CO',
 'Location_Hampton, VA',
 'Location_Hanford, CA',
 'Location_Harrison, NY',
 'Location_Haworth, NJ',
 'Location_Henderson, CO',
 'Location_Hercules, CA',
 'Location_Hilliard, OH',
 'Location_Hoboken, NJ',
 'Location_Horsham, PA',
 'Location_Houston, TX',
 'Location_Huntersville, NC',
 'Location_Indianapolis, IN',
 'Location_Inglewood, CA',
 'Location_Irving, TX',
 'Location_Irwindale, CA',
 'Location_Iselin, NJ',
 'Location_Issaquah, WA',
 'Location_Itasca, IL',
 'Location_Jacksonville, FL',
 'Location_Jeffersonville, IN',
 'Location_Jersey City, NJ',
 'Location_Kent, WA',
 'Location_King of Prussia, PA',
 'Location_Kirkland, WA',
 'Location_Lackland AFB, TX',
 'Location_Lake Success, NY',
 'Location_Lakewood, CO',
 'Location_Lawrence, IN',
 'Location_Lehi, UT',
 'Location_Lewisville, TX',
 'Location_Little Ferry, NJ',
 'Location_Littleton, CO',
 'Location_Lone Tree, CO',
 'Location_Long Beach, CA',
 'Location_Long Island City, NY',
 'Location_Los Angeles, CA',
 'Location_Los Gatos, CA',
 'Location_Louisville, CO',
 'Location_Malvern, PA',
 'Location_Manhasset, NY',
 'Location_Marin City, CA',
 'Location_Marina del Rey, CA',
 'Location_Marlton, NJ',
 'Location_Maywood, IL',
 'Location_Menlo Park, CA',
 'Location_Mesa, AZ',
 'Location_Millbrae, CA',
 'Location_Milpitas, CA',
 'Location_Montvale, NJ',
 'Location_Moorestown, NJ',
 'Location_Mooresville, NC',
 'Location_Mount Laurel, NJ',
 'Location_Mount Vernon, NY',
 'Location_Mountain View, CA',
 'Location_New York, NY',
 'Location_Newark, CA',
 'Location_Newark, NJ',
 'Location_Newport News, VA',
 'Location_Newtown Square, PA',
 'Location_Norfolk, VA',
 'Location_Northbrook, IL',
 'Location_Northfield, IL',
 'Location_Northlake, IL',
 'Location_Northridge, CA',
 'Location_Novato, CA',
 'Location_Oak Brook, IL',
 'Location_Oakland, CA',
 'Location_Palo Alto, CA',
 'Location_Paoli, PA',
 'Location_Parsippany, NJ',
 'Location_Pasadena, CA',
 'Location_Pasadena, TX',
 'Location_Pearland, TX',
 'Location_Philadelphia, PA',
 'Location_Phoenix, AZ',
 'Location_Pico Rivera, CA',
 'Location_Plano, TX',
 'Location_Pleasanton, CA',
 'Location_Plymouth Meeting, PA',
 'Location_Portsmouth, VA',
 'Location_Queens Village, NY',
 'Location_Radnor, PA',
 'Location_Redmond, WA',
 'Location_Redwood City, CA',
 'Location_Reedley, CA',
 'Location_Renton, WA',
 'Location_Richardson, TX',
 'Location_Ridley Park, PA',
 'Location_Riverton, UT',
 'Location_Rolling Meadows, IL',
 'Location_Round Rock, TX',
 'Location_Salt Lake City, UT',
 'Location_San Antonio, TX',
 'Location_San Diego, CA',
 'Location_San Francisco, CA',
 'Location_San Jose, CA',
 'Location_San Mateo, CA',
 'Location_San Rafael, CA',
 'Location_San Ramon, CA',
 'Location_Santa Clara, CA',
 'Location_Santa Monica, CA',
 'Location_Scottsdale, AZ',
 'Location_Seattle, WA',
 'Location_Secaucus, NJ',
 'Location_Smithfield, VA',
 'Location_South Plainfield, NJ',
 'Location_South San Francisco, CA',
 'Location_Southlake, TX',
 'Location_Spring, TX',
 'Location_Stafford, TX',
 'Location_Stanford, CA',
 'Location_Staten Island, NY',
 'Location_Suffolk, VA',
 'Location_Sugar Land, TX',
 'Location_Summit, NJ',
 'Location_Sunnyvale, CA',
 'Location_Tarrant, TX',
 'Location_Tempe, AZ',
 'Location_Topeka, KS',
 'Location_Torrance, CA',
 'Location_Union City, CA',
 'Location_Venice, CA',
 'Location_Virginia Beach, VA',
 'Location_Visalia, CA',
 'Location_Walnut Creek, CA',
 'Location_Wayne, PA',
 'Location_Weehawken, NJ',
 'Location_West Chester, PA',
 'Location_West Conshohocken, PA',
 'Location_West Jordan, UT',
 'Location_West Orange, NJ',
 'Location_West Point, PA',
 'Location_Westerville, OH',
 'Location_Westlake, TX',
 'Location_Whippany, NJ',
 'Location_Whitestown, IN',
 'Location_Whittier, CA',
 'Location_Wilmington, DE',
 'Location_Woodbridge, NJ',
 'Location_Woodcliff Lake, NJ',
 'Location_Woodland Hills, CA',
 'Location_Woodridge, IL',
 'Location_Yorktown, VA', 'Size_Unknown',
 'Size_1 to 50 employees',
 'Size_51 to 200 employees',
 'Size_201 to 500 employees',
 'Size_501 to 1000 employees',
 'Size_1001 to 5000 employees',        
 'Size_5001 to 10000 employees',
 'Size_10000+ employees', 'Type of ownership_Unknown',
 'Type of ownership_College / University',
 'Type of ownership_Company - Private',
 'Type of ownership_Company - Public',
 'Type of ownership_Contract',
 'Type of ownership_Franchise',
 'Type of ownership_Government',
 'Type of ownership_Hospital',
 'Type of ownership_Nonprofit Organization',
 'Type of ownership_Other Organization',
 'Type of ownership_Private Practice / Firm',
 'Type of ownership_School / School District',
 'Type of ownership_Self-employed',
 'Type of ownership_Subsidiary or Business Segment', 'Industry_Accounting',
 'Industry_Advertising & Marketing',
 'Industry_Aerospace & Defense',
 'Industry_Architectural & Engineering Services',
 'Industry_Audiovisual',
 'Industry_Automotive Parts & Accessories Stores',
 'Industry_Banks & Credit Unions',
 'Industry_Beauty & Personal Accessories Stores',
 'Industry_Biotech & Pharmaceuticals',
 'Industry_Brokerage Services',
 'Industry_Building & Personnel Services',
 'Industry_Cable, Internet & Telephone Providers',
 'Industry_Casual Restaurants',
 'Industry_Catering & Food Service Contractors',
 'Industry_Chemical Manufacturing',
 'Industry_Colleges & Universities',
 'Industry_Commercial Equipment Repair & Maintenance',
 'Industry_Computer Hardware & Software',
 'Industry_Construction',
 'Industry_Consulting',
 'Industry_Consumer Electronics & Appliances Stores',
 'Industry_Consumer Product Rental',
 'Industry_Consumer Products Manufacturing',
 'Industry_Convenience Stores & Truck Stops',
 'Industry_Department, Clothing, & Shoe Stores',
 'Industry_Drug & Health Stores',
 'Industry_Education Training Services',
 'Industry_Electrical & Electronic Manufacturing',
 'Industry_Energy',
 'Industry_Enterprise Software & Network Solutions',
 'Industry_Express Delivery Services',
 'Industry_Federal Agencies',
 'Industry_Financial Analytics & Research',
 'Industry_Financial Transaction Processing',
 'Industry_Food & Beverage Manufacturing',
 'Industry_Food & Beverage Stores',
 'Industry_Gambling',
 'Industry_Gas Stations',
 'Industry_General Merchandise & Superstores',
 'Industry_General Repair & Maintenance',
 'Industry_Grocery Stores & Supermarkets',
 'Industry_Health Care Products Manufacturing',
 'Industry_Health Care Services & Hospitals',
 'Industry_Health Fundraising Organizations',
 'Industry_Health, Beauty, & Fitness',
 'Industry_Home Centers & Hardware Stores',
 'Industry_Hotels, Motels, & Resorts',
 'Industry_IT Services',
 'Industry_Industrial Manufacturing',
 'Industry_Insurance Agencies & Brokerages',
 'Industry_Insurance Carriers',
 'Industry_Internet',
 'Industry_Investment Banking & Asset Management',
 'Industry_K-12 Education',
 'Industry_Legal',
 'Industry_Lending',
 'Industry_Logistics & Supply Chain',
 'Industry_Membership Organizations',
 'Industry_Metals Brokers',
 'Industry_Miscellaneous Manufacturing',
 'Industry_Motion Picture Production & Distribution',
 'Industry_Municipal Governments',
 'Industry_News Outlet',
 'Industry_Oil & Gas Services',
 'Industry_Other Retail Stores',
 'Industry_Pet & Pet Supplies Stores',
 'Industry_Preschool & Child Care',
 'Industry_Publishing',
 'Industry_Real Estate',
 'Industry_Research & Development',
 'Industry_Security Services',
 'Industry_Social Assistance',
 'Industry_Sporting Goods Stores',
 'Industry_Sports & Recreation',
 'Industry_Staffing & Outsourcing',
 'Industry_State & Regional Agencies',
 'Industry_Stock Exchanges',
 'Industry_TV Broadcast & Cable Networks',
 'Industry_Telecommunications Services',
 'Industry_Transportation Equipment Manufacturing',
 'Industry_Transportation Management',
 'Industry_Truck Rental & Leasing',
 'Industry_Trucking',
 'Industry_Utilities',
 'Industry_Vehicle Dealers',
 'Industry_Venture Capital & Private Equity',
 'Industry_Video Games',
 'Industry_Wholesale', 'Sector_Accounting & Legal',
 'Sector_Aerospace & Defense',
 'Sector_Arts, Entertainment & Recreation',
 'Sector_Biotech & Pharmaceuticals',
 'Sector_Business Services',
 'Sector_Construction, Repair & Maintenance',
 'Sector_Consumer Services',
 'Sector_Education',
 'Sector_Finance',
 'Sector_Government',
 'Sector_Health Care',
 'Sector_Information Technology',
 'Sector_Insurance',
 'Sector_Manufacturing',
 'Sector_Media',
 'Sector_Mining & Metals',
 'Sector_Non-Profit',
 'Sector_Oil, Gas, Energy & Utilities',
 'Sector_Real Estate',
 'Sector_Restaurants, Bars & Food Services',
 'Sector_Retail',
 'Sector_Telecommunications',
 'Sector_Transportation & Logistics',
 'Sector_Travel & Tourism', 'Revenue_Unknown / Non-Applicable',
 'Revenue_Less than $1 million (USD)',
 'Revenue_$1 to $5 million (USD)',
 'Revenue_$5 to $10 million (USD)',
 'Revenue_$10 to $25 million (USD)',
 'Revenue_$25 to $50 million (USD)',
 'Revenue_$50 to $100 million (USD)',
 'Revenue_$100 to $500 million (USD)',
 'Revenue_$500 million to $1 billion (USD)',
 'Revenue_$1 to $2 billion (USD)',
 'Revenue_$2 to $5 billion (USD)',
 'Revenue_$5 to $10 billion (USD)',
 'Revenue_$10+ billion (USD)'] 


def listToBinary(list_one, selectors):
    returnBinaryAll = []
        
    for item in list_one:
        if item in selectors:
            returnBinaryAll.append(1)
        else:
            returnBinaryAll.append(0)
    return returnBinaryAll


def predict(feature_vector: List) -> str:
    
    dropdownBinary1 = listToBinary(list_one, feature_vector)

    combinedBinaries = [dropdownBinary1]
    print(combinedBinaries)

    scaled = scaler.transform(combinedBinaries)
    data_predict = clf.predict(scaled)
    output = labelencoder.inverse_transform(data_predict)
    return output[0]


@app.route('/endpoint', methods=['POST'])
def endpoint():
    inputData = request.form.getlist('data[]')
    print(inputData, type(inputData))


    outcome = predict(inputData)
    
    return jsonify(
        results = False if outcome == "" else True,
        message = outcome,
    );



if __name__=="__main__":
    app.run(debug=True)